CREATE DATABASE sole_collector;

use sole_collector;

CREATE TABLE Shoes (
	id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
	brand VARCHAR(30) NOT NULL,
	colour VARCHAR(50) NOT NULL,
	size VARCHAR(30),
    	date TIMESTAMP
);


CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);